vich_uploader:
    db_driver: orm

    mappings:
        service:
            uri_prefix: /images/service
            upload_destination: '%kernel.project_dir%/public/images/service'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        habitat:
            uri_prefix: /images/habitat
            upload_destination: '%kernel.project_dir%/public/images/habitat'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer