<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Animal extends \App\Entity\Animal implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'animalName' => [parent::class, 'animalName', null, 16],
        "\0".parent::class."\0".'breed' => [parent::class, 'breed', null, 16],
        "\0".parent::class."\0".'consultations' => [parent::class, 'consultations', null, 16],
        "\0".parent::class."\0".'detail' => [parent::class, 'detail', null, 16],
        "\0".parent::class."\0".'food' => [parent::class, 'food', null, 16],
        "\0".parent::class."\0".'habitat' => [parent::class, 'habitat', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null, 16],
        "\0".parent::class."\0".'imageName' => [parent::class, 'imageName', null, 16],
        "\0".parent::class."\0".'imageSize' => [parent::class, 'imageSize', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'veterinaryReports' => [parent::class, 'veterinaryReports', null, 16],
        'animalName' => [parent::class, 'animalName', null, 16],
        'breed' => [parent::class, 'breed', null, 16],
        'consultations' => [parent::class, 'consultations', null, 16],
        'detail' => [parent::class, 'detail', null, 16],
        'food' => [parent::class, 'food', null, 16],
        'habitat' => [parent::class, 'habitat', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageFile' => [parent::class, 'imageFile', null, 16],
        'imageName' => [parent::class, 'imageName', null, 16],
        'imageSize' => [parent::class, 'imageSize', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'veterinaryReports' => [parent::class, 'veterinaryReports', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
