<?php

namespace ContainerV0qxzWT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFoodConsultControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jiBAzly.App\Controller\Veterinary\FoodConsultController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jiBAzly.App\\Controller\\Veterinary\\FoodConsultController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'foodRepository' => ['privates', 'App\\Repository\\FoodRepository', 'getFoodRepositoryService', true],
        ], [
            'foodRepository' => 'App\\Repository\\FoodRepository',
        ]))->withContext('App\\Controller\\Veterinary\\FoodConsultController::index()', $container);
    }
}
