<?php

namespace ContainerV0qxzWT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bKumBZj.App\Controller\PageController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bKumBZj.App\\Controller\\PageController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'habitatRepo' => ['privates', 'App\\Repository\\HabitatRepository', 'getHabitatRepositoryService', true],
            'animalRepo' => ['privates', 'App\\Repository\\AnimalRepository', 'getAnimalRepositoryService', true],
            'serviceRepo' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'habitatRepo' => 'App\\Repository\\HabitatRepository',
            'animalRepo' => 'App\\Repository\\AnimalRepository',
            'serviceRepo' => 'App\\Repository\\ServiceRepository',
        ]))->withContext('App\\Controller\\PageController::index()', $container);
    }
}
