<?php

namespace ContainerV0qxzWT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeterinaryReportConsultControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.unDaxzS.App\Controller\Admin\VeterinaryReportConsultController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.unDaxzS.App\\Controller\\Admin\\VeterinaryReportConsultController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'veterinaryReport' => ['privates', 'App\\Repository\\VeterinaryReportRepository', 'getVeterinaryReportRepositoryService', true],
        ], [
            'veterinaryReport' => 'App\\Repository\\VeterinaryReportRepository',
        ]))->withContext('App\\Controller\\Admin\\VeterinaryReportConsultController::index()', $container);
    }
}
