<?php

namespace Container1OwPyhU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpeningHoursControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.loj.Kq1.App\Controller\OpeningHoursController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.loj.Kq1.App\\Controller\\OpeningHoursController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'openingHoursRepository' => ['privates', 'App\\Repository\\OpeningHoursRepository', 'getOpeningHoursRepositoryService', true],
        ], [
            'openingHoursRepository' => 'App\\Repository\\OpeningHoursRepository',
        ]))->withContext('App\\Controller\\OpeningHoursController::index()', $container);
    }
}
