<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbwMdRx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbwMdRx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKbwMdRx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKbwMdRx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKbwMdRx\App_KernelDevDebugContainer([
    'container.build_hash' => 'KbwMdRx',
    'container.build_id' => '4bfa8a17',
    'container.build_time' => 1755523334,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbwMdRx');
